version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    groups:
      rubocop:
        patterns:
          - "rubocop*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: .github/actions/upload-coverage/
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
    groups:
      actions:
        patterns:
          - "*"
