module Sigstore
  module Internal
    class Keyring
      @keyring: untyped

      def initialize: (keys: untyped) -> void

      def verify: (key_id: untyped, signature: untyped, data: untyped) -> untyped
    end
  end
end
