module Sigstore
  module Internal
    module TUF
      DEFAULT_TUF_URL: "https://tuf-repo-cdn.sigstore.dev"

      STAGING_TUF_URL: "https://tuf-repo-cdn.sigstage.dev"

      class TrustUpdater
        @repo_url: untyped

        @metadata_dir: untyped

        @targets_dir: untyped

        @offline: untyped

        @updater: untyped

        def initialize: (untyped url, untyped offline) -> void

        def get_dirs: (untyped url) -> ::Array[untyped]

        def trusted_root_path: () -> untyped
      end

      class Updater
        @dir: untyped

        @metadata_base_url: untyped

        @target_dir: untyped

        @target_base_url: untyped

        @fetcher: untyped

        @trusted_set: untyped

        def initialize: (metadata_dir: untyped, metadata_base_url: untyped, target_base_url: untyped, target_dir: untyped, fetcher: untyped) -> void

        def refresh: () -> untyped

        def get_targetinfo: (untyped target_path) -> untyped

        def find_cached_target: (untyped target_info, ?untyped? filepath) -> untyped

        def download_target: (untyped target_info, ?untyped? filepath, ?untyped? target_base_url) -> untyped

        private

        def debug: (*untyped, **untyped `**`) -> nil

        def load_local_metadata: (untyped role_name) -> untyped

        def load_root: () -> untyped

        def load_timestamp: () -> untyped

        def load_snapshot: () -> untyped

        def load_targets: (untyped role, untyped parent_role) -> untyped

        def download_metadata: (untyped role_name, untyped version) -> untyped

        def persist_metadata: (untyped role_name, untyped data) -> untyped

        def preorder_depth_first_walk: (untyped target_path) -> (untyped | nil)

        def generate_target_file_path: (untyped target_info) -> untyped
      end
    end
  end
end
