module Sigstore
  module Internal
    module Util
      def self.base64_decode: (base64String data) -> binaryString
      def self.hex_decode: (hexString data) -> binaryString

      type base64String = string & { "base64" => true }
      type hexString = string & { "hex" => true }
      type binaryString = string & { "binary" => true }
    end
  end
end