AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'test/sigstore-conformance/**/*'
    - 'test/tuf-conformance/**/*'

require:
  - rubocop-performance
  - rubocop-rake

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false # TODO: Enable this cop
