AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "test/sigstore-conformance/**/*"
    - "test/tuf-conformance/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"

require:
  - rubocop-performance
  - rubocop-rake

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true
