module Sigstore
  module Cosign
    module Verify
      class VerificationResult
        def initialize: (success: bool) -> void

        attr_reader success: bool
        def verified?: () -> bool
      end

      class VerificationSuccess < VerificationResult
        def initialize: () -> void
        def verified?: () -> true
      end

      class VerificationFailure < VerificationResult
        @reason: string

        attr_reader reason: string

        def initialize: (string reason) -> void

        def verified?: () -> false
      end

      type verificationResult = VerificationSuccess | VerificationFailure

      class InvalidMaterials < StandardError
        def initialize: () -> void
      end

      VerificationMaterials: untyped

      class BundleType
        attr_reader media_type: String
        def initialize: (String) -> void
        BUNDLE_0_1: BundleType
        BUNDLE_0_2: BundleType
        BUNDLE_0_3: BundleType
      end

      def self.from_bundle: (input: untyped, bundle: untyped, offline: untyped) -> untyped
    end
  end
end
