module Sigstore
  module Cosign
    module Verify
      class Verifier
        @rekor_client: untyped

        @fulcio_cert_chain: untyped

        def initialize: (rekor_client: untyped, fulcio_cert_chain: untyped) -> void

        def self.production: (?trust_root: untyped) -> untyped

        def verify: (materials: untyped, policy: untyped) -> untyped
      end
    end
  end
end
