module Sigstore::Internal::TUF
  class Root
    @spec_version: untyped

    @consistent_snapshot: untyped

    @version: untyped

    @expires: untyped

    @keys: untyped

    @roles: untyped

    @unrecognized_fields: untyped

    TYPE: "root"

    attr_reader version: untyped

    attr_reader consistent_snapshot: untyped

    def initialize: (untyped data) -> void

    def verify_delegate: (untyped type, untyped bytes, untyped signatures) -> untyped

    def expired?: (untyped reference_time) -> untyped
  end
end
