module Sigstore::Internal::TUF
  # The class for the Snapshot role
  class Snapshot
    @version: untyped

    @expires: untyped

    @meta: untyped

    TYPE: "snapshot"

    attr_reader version: untyped

    attr_reader meta: untyped

    def initialize: (untyped data) -> void

    def expired?: (untyped reference_time) -> untyped

    class Meta
      @version: untyped

      @length: untyped

      @hashes: untyped

      @unrecognized_fields: untyped

      attr_reader version: untyped

      def initialize: (untyped data) -> void

      def verify_length_and_hashes: (untyped data) -> untyped

      def verify_length: (untyped data, untyped length) -> nil

      def verify_hashes: (untyped data, untyped hashes) -> nil

      def validate_length: (untyped length) -> nil

      def validate_hashes: (untyped hashes) -> nil
    end
  end
end
