module Gem
  module Commands
    class SigstoreCosignVerifyCommand < Gem::Command
      def initialize: () -> void

      def execute: () -> untyped

      private

      def collect_verification_state: () -> ::Array[untyped]
    end
  end
end
